### ISSUE TITLE
Some inconsistent results

### ISSUE THREAD

**Issue by ikhrzcao** [junjun-jiang/Face-Hallucination-Benchmark#2]
Hi,

Thank you for your wonderful work. It is really helpful and saved me a lot of time!

I tried to test the produced SR images (from some SOTA methods) you provided on Baidu Driver, and computed PSNR and SSIM using the code in this implementation (eval_psnr_ssim.py). However, what I obtained were quiet different from the results reported in your survey paper (Table 7). For example, the RCAN method achieved about 31.50dB on CelebA x4, but the result in Table 7 is  31.69dB.

I was wondering if I missed something important. Thank you, and look forward to ur reply : )

**Comment by junjun-jiang** [comment]
Thank you for your attention. We have checked the code and the results we provided, and haven't found inconsistent problem.  Towards the metrics of RCAN, we directly run the code on the results, generating the following results. 
![image](https://user-images.githubusercontent.com/4609614/141750527-b92ceb91-db6a-43ce-9fc0-0e11a2f04b5a.png)

**Comment by ikhrzcao** [comment]
> Thank you for your attention. We have checked the code and the results we provided, and haven't found inconsistent problem. Towards the metrics of RCAN, we directly run the code on the results, generating the following results.
> ![image](https://user-images.githubusercontent.com/4609614/141750527-b92ceb91-db6a-43ce-9fc0-0e11a2f04b5a.png)

Thank you so much for your reply. I’ll further look into the code to see if I misunderstand something. Thank you again!
