### ISSUE TITLE
small spell problem

### ISSUE THREAD

**Issue by PennyPeng369** [junjun-jiang/Face-Hallucination-Benchmark#3]
I think it should be GFP-GAN rather than CFP-GAN.
-   [CFP-GAN] Towards Real-World Blind Face Restoration with Generative Facial Prior, X. Wang et al., CVPR 2021.

https://github.com/junjun-jiang/Face-Hallucination-Benchmark/blob/4062771d7df9593bd87d35df812c166b9f948b59/README.md?plain=1#L166

**Comment by junjun-jiang** [comment]
Yes, it should be GFP-GAN. Thanks.
