### ISSUE TITLE
Anything new in 2022?

### ISSUE THREAD

**Issue by PennyPeng369** [junjun-jiang/Face-Hallucination-Benchmark#4]
Is there anything new in 2022?
Looking forward to SOTA works in 2022 .
Thanks :)

**Comment by hrd-yorku** [comment]
I have prepared the repository for the newly published paper "Super-resolution of very low-resolution face images with a wavelet integrated, identity preserving, adversarial network":
https://github.com/hrd-yorku/WIPA-Face-Super-Resolution
please tell me your opinion and if you think it is helpful please add it to your repository.

**Comment by junjun-jiang** [comment]
SOTA works in 2022 are added. Thank you for your attention.
